In [1]:
import numpy as np
import pandas as pd
a = [2,3,1]
b = [4,-1,5]
print(np.dot(a,b))
# it's equal to 2*4 + 3*(-1) + 1*5 = 8 + -3 + 5 = 10

10


# Matrix Multiplication in a Single Neural Network Layer

In a basic neural network, each layer performs computations using matrix multiplication to transform inputs into outputs. Here's how it works:

## Forward Pass in a Single Layer

1. **Inputs**: The input to a layer is a vector (or batch of vectors) representing features from the previous layer or raw data.

2. **Weights Matrix**: Each layer has a weight matrix `W` where:
   - Rows correspond to neurons in the current layer
   - Columns correspond to inputs from the previous layer
   - Each element `W[i,j]` represents the strength of connection from input `j` to neuron `i`

3. **Matrix Multiplication**: The core computation is:
   ```
   Z = W * X + b
   ```
   Where:
   - `X` is the input vector/matrix
   - `W` is the weights matrix
   - `b` is the bias vector (added to each neuron)
   - `Z` is the pre-activation output

4. **Activation Function**: Apply a non-linear activation (like ReLU, sigmoid) to `Z` to get the final output `A`:
   ```
   A = activation(Z)
   ```

## Why Matrix Multiplication?

- **Efficiency**: Matrix operations can be parallelized and optimized (e.g., using GPUs)
- **Scalability**: Handles multiple inputs/outputs simultaneously
- **Mathematical Foundation**: Represents linear transformations in vector spaces

## Example

For a layer with 3 neurons and 2 inputs:
- `X` = [x1, x2] (1x2 vector)
- `W` = [[w11, w12], [w21, w22], [w31, w32]] (3x2 matrix)
- `b` = [b1, b2, b3] (3x1 vector)

The output `Z` = [w11*x1 + w12*x2 + b1, w21*x1 + w22*x2 + b2, w31*x1 + w32*x2 + b3]

This is computed efficiently as matrix multiplication followed by bias addition.

In [4]:
a = np.random.rand(4,4)
b = np.random.rand(4,4)
print("a multiply by b is equal to", a*b)
print("transpose value of a*b is equal to ", (a*b).T)

a multiply by b is equal to [[0.38551567 0.01301477 0.11131309 0.01814635]
 [0.03250888 0.66089691 0.23437734 0.08254718]
 [0.59035857 0.08523107 0.02597058 0.27811855]
 [0.70732997 0.28160239 0.24776052 0.19897553]]
transpose value of a*b is equal to  [[0.38551567 0.03250888 0.59035857 0.70732997]
 [0.01301477 0.66089691 0.08523107 0.28160239]
 [0.11131309 0.23437734 0.02597058 0.24776052]
 [0.01814635 0.08254718 0.27811855 0.19897553]]
